#此工作流将使用节点运行测试，然后在创建发布时将包发布到GitHub包
#有关详细信息，请参阅：https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

姓名:Node.js包

在……之上:
释放:
类型:[创造]

工作:
建立:
run-on:ubuntu-最新
步骤:
-uses:操作/结帐@v4
-uses:操作/设置-节点@v3
和……一起:
节点版本:16
-跑:npm ci
-跑:npm测试

publish-npm:
需要:建立
run-on:ubuntu-最新
步骤:
-uses:操作/结帐@v4
-uses:操作/设置-节点@v3
和……一起:
节点版本:16
registry-url:HTTPS://registry.npmjs.org/
-跑:npm ci
-跑:npm发布
env:
node_AUTH_TOKEN:${{secrets.npm_token}}
